from staff import Staff

stafflist = []

stafflist.append(Staff("Bajwa", "Dr.", "biology", 1))
stafflist.append(Staff("Kennedy", "Mrs.", "biology", 1))
stafflist.append(Staff("Kenny", "Dr.", "biology", 1))
stafflist.append(Staff("Pinto", "Dr.", "biology", 1))
stafflist.append(Staff("Waldron", "Mrs.", "biology", 1))
stafflist.append(Staff("Zepatos", "Mrs.", "biology", 1))
stafflist.append(Staff("Zhang", "Mr.", "biology", 1))
stafflist.append(Staff("Stott", "Mrs.", "biology", 2))

stafflist.append(Staff("Fogg", "Mr.", "business", 1))
stafflist.append(Staff("Gutierrez", "Mr.", "business", 1))
stafflist.append(Staff("Sawhney", "Mrs.", "business", 1))

stafflist.append(Staff("Crane", "Dr.", "chemistry", 2))
stafflist.append(Staff("Dobrich", "Mr.", "chemistry", 2))
stafflist.append(Staff("Feuss", "Mrs.", "chemistry", 2))
stafflist.append(Staff("Kim", "Dr.", "chemistry", 2))
stafflist.append(Staff("Sorrentino", "Mrs.", "chemistry", 2))

stafflist.append(Staff("Branda", "Chef", "culinary", 2))
stafflist.append(Staff("Adriance", "Chef", "culinary", 2))

stafflist.append(Staff("Berwick", "Mrs.", "english", 0))
stafflist.append(Staff("Crimmel", "Mrs.", "english", 0))
stafflist.append(Staff("DiAmico-King", "Mrs.", "english", 0))
stafflist.append(Staff("Hathaway", "Mr.", "english", 0))
stafflist.append(Staff("Kaba", "Mrs.", "english", 0))
stafflist.append(Staff("Kouefati", "Mrs.", "english", 0))
stafflist.append(Staff("Mendelsohn", "Mr.", "english", 0))
stafflist.append(Staff("Halligan", "Mrs.", "english", 0))
stafflist.append(Staff("Torres", "Mr.", "english", 0))
stafflist.append(Staff("Villanova", "Mrs.", "english", 0))
stafflist.append(Staff("Weems", "Mr.", "english", 0))
stafflist.append(Staff("Wilson", "Mr.", "english", 0))

stafflist.append(Staff("Acuna", "Mrs.", "guidance", 1))
stafflist.append(Staff("Andaloro", "Mrs.", "guidance", 1))
stafflist.append(Staff("Belkin", "Mrs.", "guidance", 1))
stafflist.append(Staff("Kaser", "Mr.", "guidance", 1))
stafflist.append(Staff("Keane", "Mr.", "guidance", 1))
stafflist.append(Staff("Natelli", "Mr.", "guidance", 1))
stafflist.append(Staff("Sytsma", "Mrs.", "guidance", 1))
stafflist.append(Staff("Sousa", "Mrs.", "guidance", 1))
stafflist.append(Staff("Zurich", "Mr.", "guidance", 1))

stafflist.append(Staff("Abramson", "Dr.", "math", 2))
stafflist.append(Staff("Bonanomi", "Mr.", "math", 2))
stafflist.append(Staff("Casarico", "Mrs.", "math", 1))
stafflist.append(Staff("Djedji", "Mr.", "math", 1))
stafflist.append(Staff("Heitzman", "Dr.", "math", 2))
stafflist.append(Staff("Nevard", "Dr.", "math", 2))
stafflist.append(Staff("Ogden", "Mrs.", "math", 2))
stafflist.append(Staff("Penev", "Dr.", "math", 2))
stafflist.append(Staff("Pinyan", "Mr.", "math", 2))
stafflist.append(Staff("Robinson", "Dr.", "math", 2))
stafflist.append(Staff("Seventko", "Mr.", "math", 2))
stafflist.append(Staff("Walsh", "Mr.", "math", 2))
stafflist.append(Staff("Zangara", "Mrs.", "math", 2))

stafflist.append(Staff("Finley", "Mr.", "music", 2))
stafflist.append(Staff("Lemma", "Mr.", "music", 0))
stafflist.append(Staff("Spinelli", "Mr.", "music", 2))

stafflist.append(Staff("Fuentes", "Mrs.", "gym", 1))
stafflist.append(Staff("James", "Mrs.", "gym", 1))
stafflist.append(Staff("Kalata", "Mr.", "gym", 1))
stafflist.append(Staff("Marmora", "Mr.", "gym", 1))
stafflist.append(Staff("Symons", "Mr.", "gym", 1))
stafflist.append(Staff("Rios", "Mrs.", "gym", 1))

stafflist.append(Staff("Crochet", "Mrs.", "theater", 1))
stafflist.append(Staff("Kaplan", "Mr.", "theater", 0))
stafflist.append(Staff("Pero", "Mrs.", "theater", 0))

stafflist.append(Staff("Dogru", "Dr.", "physics", 0))
stafflist.append(Staff("Hodroski", "Mr.", "physics", 2))
stafflist.append(Staff("Liva", "Mr.", "physics", 1))
stafflist.append(Staff("Paul", "Mr.", "physics", 2))
stafflist.append(Staff("Russo", "Mr.", "physics", 0))
stafflist.append(Staff("Zubov", "Dr.", "physics", 2))

stafflist.append(Staff("Alschen", "Mr.", "history", 1))
stafflist.append(Staff("Blake", "Mrs.", "history", 1))
stafflist.append(Staff("Demeter", "Mr.", "history", 1))
stafflist.append(Staff("Janssen", "Mrs.", "history", 2))
stafflist.append(Staff("Kramer", "Mr.", "history", 2))
stafflist.append(Staff("Madden", "Mr.", "history", 1))
stafflist.append(Staff("Miller", "Mr.", "history", 2))
stafflist.append(Staff("Pagano", "Mrs.", "history", 1))
stafflist.append(Staff("Wallace", "Mrs.", "history", 2))

stafflist.append(Staff("Barbetta", "Mr.", "engineering", 1))
stafflist.append(Staff("Nodarse", "Mr.", "engineering", 1))
stafflist.append(Staff("Samarakone", "Mr.", "engineering", 1))

stafflist.append(Staff("Isecke", "Mr.", "compsci", 1))
stafflist.append(Staff("Respass", "Mr.", "compsci", 1))
stafflist.append(Staff("Wang", "Mr.", "compsci", 1))

stafflist.append(Staff("Guthrie", "Mr.", "visual", 1))
stafflist.append(Staff("Min", "Mrs.", "visual", 1))
stafflist.append(Staff("Lang", "Mr.", "visual", 1))

stafflist.append(Staff("Ballas", "Madame", "language", 2))
stafflist.append(Staff("Calandra", "Profe", "language", 1))
stafflist.append(Staff("Carberry", "Profe", "language", 2))
stafflist.append(Staff("Fillebrown", "Mrs.", "language", 2))
stafflist.append(Staff("Lewitt", "Profe", "language", 2))
stafflist.append(Staff("Ponce", "Profe", "language", 1))
stafflist.append(Staff("Seltzer", "Profe", "language", 2))
stafflist.append(Staff("Tolmo", "Profe", "language", 2))
stafflist.append(Staff("Villarosa", "Madame", "language", 2))
stafflist.append(Staff("Xu", "Mrs.", "language", 2))

# stafflist.append(Staff("Acuna", "Mrs.", "counseling", 1))
# stafflist.append(Staff("Adriance", "Mrs.", "culinary", 2))
# stafflist.append(Staff("Alschen", "Mr.", "history", 1))
# stafflist.append(Staff("Ballas", "Madame", "french", 2))
# stafflist.append(Staff("Barbetta", "Mr.", "engineering", 1))
# stafflist.append(Staff("Berwick", "Mrs.", "english", 0))
# stafflist.append(Staff("Demeter", "Mr.", "history", 1))
# stafflist.append(Staff("Feuss", "Mrs.", "chemistry", 2))
# print(stafflist[0].floor)